### ISSUE TITLE
文档中示例错误. 

### ISSUE THREAD

**Issue by allenLew1991** [zeromicro/go-zero-doc#85]
https://github.com/zeromicro/go-zero-doc/blob/master/cn/business-coding.md
文档中是示例错误. FindOneByNumber这个方法goctl model 并没有自动生成

Unresolved reference 'FindOneByNumber'

**Comment by anqiansong** [comment]
@allenLew1991 如果你按照流程阅读文档的话，你在进入demo之前会让你下载一个【演示工程】，其中包含了对user的sql文件，你需要根据此sql文件生成model，其生成会包含`FindOneByNumber`方法。点击[这里](https://go-zero.dev/cn/business-dev.html)跳转到文档下载引导页
![image](https://user-images.githubusercontent.com/10302073/123073771-4d543f00-d449-11eb-8d1c-305ac5885fb0.png)

**Comment by allenLew1991** [comment]
@anqiansong 就是下载了这个代码.  里面没有生成 FindOneByNumber ;

**Comment by allenLew1991** [comment]
![image](https://user-images.githubusercontent.com/3362015/123076900-23504c00-d44c-11eb-9f6c-19db04067a80.png)
这里请求参数传的username.  调用却是 FindOneByNumber.  实际应该是 FindOneByName. 

后面直接参考https://go-zero.dev/cn/goctl-model.html 手动添加了FindOneByName
![image](https://user-images.githubusercontent.com/3362015/123077416-9d80d080-d44c-11eb-9ec2-c277a31dc782.png)

**Comment by gemtra** [comment]
遇到了同样的问题，感谢楼主的方法
