### ISSUE TITLE
go-zero如何对etcd做安全策略？

### ISSUE THREAD

**Issue by yodfz** [zeromicro/go-zero-doc#89]
按照文档跑起来的etcd是没有安全策略的

而etcd提供了 多种安全模式配置。

go-zero如何对安全配置做设置？

还是说，就没有这样的配置？

那么如何保证注册上来的节点是自己的？

**Comment by kevwan** [comment]
好问题！目前内网使用，我们没做etcd的安全策略，可以一起讨论哈

**Comment by yodfz** [comment]
> 好问题！目前内网使用，我们没做etcd的安全策略，可以一起讨论哈

那这样，你们内网是不对注册上来的节点做管控么？

我现在的想法只能是机器做防火墙白名单了。

**Comment by kevwan** [comment]
我们只是本集群内使用，安全风险目前可控哈

**Comment by yodfz** [comment]
> 我们只是本集群内使用，安全风险目前可控哈

all right.
